- name:  Nginx installation
  hosts: all

  vars:
    registry_url: "http://localhost:5000"

  handlers:
    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true

  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    
    - name: Copy over nginx.conf
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart nginx

    - name: Copy over registry.conf
      ansible.builtin.template:
        src: registry.conf.j2
        dest: /etc/nginx/conf.d/registry.conf
      notify:
        - Restart nginx

    - name: Create a ssl folder
      ansible.builtin.file:
        name: /etc/nginx/ssl
        state: directory
        mode: 0750
        owner: root
        group: root

    - name: Create a dhparam (this will take a while)
      community.crypto.openssl_dhparam:
        path: /etc/nginx/ssl/dhparams.pem
        size: 4096
      notify:
        - Restart nginx

    - name: Allow 443 in firewalld
      ansible.posix.firewalld:
        port: 443/tcp
        permanent: true
        immediate: true
        state: enabled

    - name: Allow SELinux to connect to any port
      ansible.posix.seboolean:
        name: httpd_can_network_connect
        state: true
        persistent: true
